version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo Initializing environment
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
        --domain nextwork \
        --domain-owner 439152312386 \
        --region ap-southeast-1 \
        --query authorizationToken \
        --output text)

  build:
    commands:
      - echo Build started on `date`
      - mvn -s settings.xml clean package

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/nextwork-web-project.war
